### ISSUE TITLE
Docker build failing

### ISSUE THREAD

**Issue by charlesbrandt** [makermadecnc/makerverse#88]
Following along with:

https://makerverse.com/installation/web-server/docker/

After `git clone https://github.com/makermadecnc/makerverse.git` , I get the following:

```
$ makerverse/bin/launch
Makerverse:latest settings: /home/account/.makerverse (project at: /home/account/makerverse)
Docker v20.10.11 detected
Removing old versions (pruning docker)...
Total reclaimed space: 0B
Updating makerverse/core:latest...
latest: Pulling from makerverse/core
Digest: sha256:6eaf5ff53613a58f2130d9e5ea7dca608f024e1eb519a6c4a5f5c6182a09053e
Status: Image is up to date for makerverse/core:latest
docker.io/makerverse/core:latest
Killing prior instances...
makerverse
Launching makerverse/core:latest...
2021-12-06T00:03:34.603Z - info init Loading configuration from "/home/node/.makerverse"
2021-12-06T00:03:34.606Z - error service:configstore Unable to write data to "/home/node/.makerverse"
Error: Error: EACCES: permission denied, open '/home/node/.makerverse'
    at Object.openSync (fs.js:462:3)
    at Object.writeFileSync (fs.js:1384:35)
    at ConfigStore.sync (/home/node/dist/makerverse/server/index.js:294:51)
    at ConfigStore.set (/home/node/dist/makerverse/server/index.js:335:29)
    at Module.createServer (/home/node/dist/makerverse/server/index.js:22532:38)
    at /home/node/dist/makerverse/server-cli.js:92:25
    at new Promise (<anonymous>)
    at _default (/home/node/dist/makerverse/server-cli.js:88:10)
    at Object.<anonymous> (/home/node/bin/makerverse:9:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/home/node/.makerverse'
}
```

I already had docker installed, so I may have missed a step, but wanted to share this in case others can replicate the issue.

**Comment by zaneclaes** [comment]
So the part that's failing isn't the build, but launching the built app. The interesting line is here:
```
Error: Error: EACCES: permission denied, open '/home/node/.makerverse'
```

This suggests that you are trying to launch from an invalid directory. Specifically, it is saying it is trying to write a file to `/home/account/.makerverse` on your device, but it does not have permission to do so. It suggests that your current username is `account` (which stuck out as odd to me, but if that's correct then that's okay). If you type `echo "$HOME"` it should read `/home/account`. 

If that's correct, determine if the file exists:
`ls -la /home/account/.makerverse`

If it doesn't exist, there's some sort of permissions problem where you cannot create/edit a file in the home directory. If it does exist, maybe you changed a username or something and it's owned by someone else? The above command will report the read/write status and the owner. If the owner is wrong, you could `chown` back to yourself. Otherwise, if all else fails, try deleting it with `rm -rf ls -la /home/account/.makerverse` (this will clear your settings).
